email-domain: heustach.fr
emoji: ðŸ‘»
domain: heustach.loc
protocol: http
database-url: ${env:DATABASE_URL}
esbuild:
  bundle: true
  minify: true
  sourcemap: true
  target: node20
  platform: node
  concurrency: 10
  external:
    - mysql2

serverlessTerminationProtection:
  stages:
    - prod

prune:
  automatic: true
  number: 1